name: vfood
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: any
  google_sign_in: ^6.2.1

  # Locator
  get_it: ^8.0.2

  # Comparison
  equatable: ^2.0.5

  # Bloc
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  # Dio
  dio: ^5.7.0
  retrofit: ^4.2.0
  json_annotation: ^4.9.0

  # Storage
  shared_preferences: ^2.5.2

  # Fonts
  google_fonts: ^6.2.1

  # Routes
  go_router: ^14.3.0

  # Logger
  logger: ^2.4.0

  # Localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Feature
  url_launcher: ^6.3.1
  formz: ^0.8.0
  moment_dart: ^4.0.1
  internet_connection_checker_plus: ^2.7.0
  permission_handler: ^11.4.0

  # Animation
  page_transition: ^2.2.1
  animated_switcher_plus: ^1.1.1

  # UI
  iconify_flutter_plus: ^1.0.4
  google_nav_bar: ^5.0.7
  loader_overlay: ^5.0.0
  cherry_toast: ^1.12.0
  lottie: ^3.3.1
  flutter_advanced_avatar: ^1.5.2
  cached_network_image: ^3.4.1
  hl_image_picker: ^1.2.16
  multi_dropdown: ^3.0.1
  photo_view: 0.15.0
  readmore: ^3.0.0
  buttons_tabbar: ^1.3.15
  giffy_dialog: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dio (Retrofit) Generator
  retrofit_generator: ^8.2.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.0

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/shared/
    - assets/shared/images/
    - assets/shared/json/
    - assets/shared/json/loading/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
